### ISSUE TITLE
[groovy] mobile_base crashing on minimal.launch

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#173] opened 2012-11-22 07:23 UTC
Here is the error:

```
terminate called after throwing an instance of 'ecl::StandardException'
  what():  
Location : /opt/ros/groovy/stacks/ecl_core/ecl_containers/include/ecl/containers/push_and_pop/push_and_pop_dynamic.hpp:235 
Flag     : Out of range error - tried to access beyond the range of the object (usually container).
Detail   : PushAndPop follower==leader

================================================================================REQUIRED process [mobile_base-4] has died!
process has died [pid 25196, exit code -6, cmd /opt/kobuki_workspace/kobuki/kobuki_node/bin/kobuki_node mobile_base/odom:=odom mobile_base/cmd_vel:=cmd_vel mobile_base/enable:=enable mobile_base/disable:=disable mobile_base/joint_states:=joint_states __name:=mobile_base __log:=/home/marcus/.ros/log/dcc1abc0-3473-11e2-b335-0026664bb1ae/mobile_base-4.log].
log file: /home/marcus/.ros/log/dcc1abc0-3473-11e2-b335-0026664bb1ae/mobile_base-4*.log
Initiating shutdown!
================================================================================
cannot add process [turtlebot_laptop_battery-6] after process monitor has been shut down
```

**Comment by bit-pirate** [comment] 2012-11-23 00:42
Apparently this was only caused by a buggy kobuki.

**Comment by bit-pirate** [comment] 2012-11-23 05:33
Maybe this error has to do with the current firmware version.
After flashing (my) current version, I had the same problem again. Reopening ...

**Comment by stonier** [comment] 2012-11-24 13:32
Still seeing this....not good before having to show the robots.

**Comment by stonier** [comment] 2012-11-28 06:03
Need to reproduce...last round of testing, and if we can't, then close it for now.

**Comment by stonier** [comment] 2012-11-29 15:40
Haven't seen for a long time - not since it was supposed that it might have been a firmware version clash.

Closing for now, reopen if necessary.

**Closed as completed by stonier** 2012-11-29 15:40 UTC
Labels: type:bug
